# Generated by Django 2.0 on 2017-12-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='score',
            field=models.DecimalField(decimal_places=2, help_text='Enter a score between 0.00 and 50.00', max_digits=5),
        ),
    ]
