# Generated by Django 2.0 on 2017-12-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_auto_20171213_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='associated_text',
            field=models.CharField(default='', max_length=20),
        ),
    ]
